### ISSUE TITLE
Bugs before capstone

### ISSUE THREAD

**Issue by camd67** [camd67/stream-surfer#54]
Add comments here for any bugs you find like this:
- [x] Bug here

**Comment by wongalisonk** [comment]
- [ ] Fix borders on boxes on home screen

**Comment by camd67** [comment]
![image](https://cloud.githubusercontent.com/assets/7773345/26611173/4294bdea-4561-11e7-9691-5992d711a374.png)
- [ ] Duplicate shows on services tab
